# Generated by Django 5.2.16 on 2026-08-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyg_per_brl', models.DecimalField(decimal_places=2, default=1400.0, max_digits=10, verbose_name='1 Real (R$) en Guaraníes (₲)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Cambio (₲ / R$)',
                'verbose_name_plural': 'Tipo de Cambio (₲ / R$)',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('country', models.CharField(choices=[('PY', 'Paraguay'), ('BR', 'Brasil')], default='PY', max_length=2, verbose_name='País de Residencia')),
                ('document_id', models.CharField(max_length=50, verbose_name='Cédula / RG / CPF')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Modelo del Vehículo (Ej. Toyota Premio, Fiat Uno)')),
                ('vehicle_color', models.CharField(max_length=50, verbose_name='Color')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Chapa / Placa')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado por Admin')),
                ('is_online', models.BooleanField(default=False, verbose_name='En Línea (Disponible)')),
                ('current_lat', models.FloatField(blank=True, null=True, verbose_name='Latitud Actual')),
                ('current_lng', models.FloatField(blank=True, null=True, verbose_name='Longitud Actual')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='FareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare_pyg', models.IntegerField(default=7000, verbose_name='Bajada de Bandera / Tarifa Base (₲)')),
                ('price_per_km_pyg', models.IntegerField(default=3500, verbose_name='Precio por Kilómetro (₲)')),
                ('price_per_min_pyg', models.IntegerField(default=500, verbose_name='Precio por Minuto (₲)')),
                ('app_commission_percent', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Comisión de la App (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tarifa Activa')),
            ],
            options={
                'verbose_name': 'Configuración de Tarifa',
                'verbose_name_plural': 'Configuraciones de Tarifa',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('preferred_currency', models.CharField(choices=[('PYG', 'Guaraníes (₲)'), ('BRL', 'Reales (R$)')], default='PYG', max_length=3, verbose_name='Moneda Preferida')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_address', models.CharField(max_length=255, verbose_name='Origen')),
                ('origin_lat', models.FloatField(verbose_name='Latitud Origen')),
                ('origin_lng', models.FloatField(verbose_name='Longitud Origen')),
                ('destination_address', models.CharField(max_length=255, verbose_name='Destino')),
                ('destination_lat', models.FloatField(verbose_name='Latitud Destino')),
                ('destination_lng', models.FloatField(verbose_name='Longitud Destino')),
                ('distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Distancia (km)')),
                ('estimated_minutes', models.IntegerField(default=0, verbose_name='Tiempo Estimado (min)')),
                ('total_fare_pyg', models.IntegerField(default=0, verbose_name='Total en Guaraníes (₲)')),
                ('total_fare_brl', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total en Reales (R$)')),
                ('app_commission_pyg', models.IntegerField(default=0, verbose_name='Comisión App (₲)')),
                ('payment_method', models.CharField(choices=[('CASH_PYG', 'Efectivo Guaraníes (₲)'), ('CASH_BRL', 'Efectivo Reales (R$)'), ('PIX', 'PIX (Brasil)'), ('TRANSFER', 'Transferencia / Giro (Paraguay)')], default='CASH_PYG', max_length=20, verbose_name='Forma de Pago')),
                ('status', models.CharField(choices=[('PENDING', 'Buscando Conductor'), ('ACCEPTED', 'Conductor En Camino'), ('IN_PROGRESS', 'En Viaje'), ('COMPLETED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora Solicitud')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Finalización')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='api.driver', verbose_name='Conductor')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='api.passenger', verbose_name='Pasajero')),
            ],
            options={
                'verbose_name': 'Solicitud de Viaje',
                'verbose_name_plural': 'Solicitudes de Viajes',
            },
        ),
    ]
