# Generated by Django 5.2.16 on 2026-08-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción del Gasto')),
                ('category', models.CharField(default='Operaciones', max_length=100, verbose_name='Categoría')),
                ('amount_pyg', models.IntegerField(verbose_name='Monto en Guaraníes (₲)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
            },
        ),
        migrations.AlterModelOptions(
            name='currencyexchange',
            options={'verbose_name': 'Tipo de Cambio (₲ / R$ / USD)', 'verbose_name_plural': 'Tipo de Cambio (₲ / R$ / USD)'},
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='preferred_currency',
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='pyg_per_usd',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10, verbose_name='1 Dólar ($) en Guaraníes (₲)'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='total_fare_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total USD $'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='country',
            field=models.CharField(choices=[('PY', 'Paraguay'), ('BR', 'Brasil')], default='PY', max_length=2, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='En Línea'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Verificado por Admin'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_model',
            field=models.CharField(max_length=100, verbose_name='Modelo del Vehículo'),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='app_commission_percent',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Comisión App (%)'),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='base_fare_pyg',
            field=models.IntegerField(default=7000, verbose_name='Tarifa Base (₲)'),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='price_per_km_pyg',
            field=models.IntegerField(default=3500, verbose_name='Precio por Km (₲)'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='app_commission_pyg',
            field=models.IntegerField(default=0, verbose_name='Comisión App ₲'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='api.driver'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='estimated_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='api.passenger'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='payment_method',
            field=models.CharField(choices=[('CASH_PYG', 'Efectivo Guaraníes (₲)'), ('CASH_BRL', 'Efectivo Reales (R$)'), ('CASH_USD', 'Efectivo Dólares ($)'), ('PIX', 'PIX (Brasil)'), ('TRANSFER', 'Transferencia / Giro (Paraguay)')], default='CASH_PYG', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Buscando Conductor'), ('ACCEPTED', 'Conductor En Camino'), ('IN_PROGRESS', 'En Viaje'), ('COMPLETED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='total_fare_brl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total R$'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='total_fare_pyg',
            field=models.IntegerField(default=0, verbose_name='Total ₲'),
        ),
    ]
