# Generated by Django 5.2.16 on 2026-08-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expense_alter_currencyexchange_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Ciudad / Punto')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en la App')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Ciudad / Itinerario de Mapa',
                'verbose_name_plural': 'Ciudades e Itinerarios de Mapa',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_pyg',
            field=models.IntegerField(default=0, verbose_name='Monto en Guaraníes (₲)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Operaciones', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha del Gasto'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción del Gasto'),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='base_fare_pyg',
            field=models.IntegerField(default=20000, verbose_name='Tarifa Base (₲)'),
        ),
    ]
