# Generated by Django 5.2.16 on 2026-08-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_citylocation_alter_expense_amount_pyg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_service_km',
            field=models.FloatField(default=0.0, verbose_name='Km del Último Mantenimiento'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pin_code',
            field=models.CharField(default='1234', max_length=10, verbose_name='PIN Acceso (4 dígitos)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_km_driven',
            field=models.FloatField(default=0.0, verbose_name='Kilometraje Acumulado (km)'),
        ),
    ]
