# Generated by Django 5.2.16 on 2026-08-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_driver_last_service_km_driver_pin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Calificaciones'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating_sum',
            field=models.IntegerField(default=0, verbose_name='Suma de Estrellas'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calificación (1-5 estrellas)'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='rating_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario Pasajero'),
        ),
    ]
