# Generated by Django 5.2.16 on 2026-08-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_driver_rating_count_driver_rating_sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código de Cupón')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Descuento (%)')),
                ('discount_flat_pyg', models.IntegerField(default=0, verbose_name='Descuento Fijo (₲)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupón de Descuento',
                'verbose_name_plural': 'Cupones de Descuento',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias Cta. Bancaria (Paraguay)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pix_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX (Brasil)'),
        ),
    ]
