# Generated by Django 5.2.16 on 2026-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_coupon_driver_bank_alias_driver_pix_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo_ci',
            field=models.FileField(blank=True, null=True, upload_to='drivers/ci/', verbose_name='Foto Cédula / RG / CPF'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo_judicial',
            field=models.FileField(blank=True, null=True, upload_to='drivers/judicial/', verbose_name='Antecedentes Judiciales'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo_license_plate',
            field=models.FileField(blank=True, null=True, upload_to='drivers/plate/', verbose_name='Foto de la Chapa / Placa'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo_police',
            field=models.FileField(blank=True, null=True, upload_to='drivers/police/', verbose_name='Antecedentes Policiales'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo_vehicle',
            field=models.FileField(blank=True, null=True, upload_to='drivers/vehicle/', verbose_name='Foto del Vehículo'),
        ),
    ]
